### ISSUE TITLE
It's didn't support StyleGuides?

### ISSUE THREAD

**Issue by bimawa** [amaurydavid/SwiftForAll#1]
It's seen only local styles for export.
![image](https://user-images.githubusercontent.com/1393809/69624157-f6686700-1065-11ea-8180-3e46022b57a3.png)

**Comment by acidlynx** [comment]
Not all local styles exported too
<img width="1505" alt="image" src="https://user-images.githubusercontent.com/958429/69624625-1b54de00-1056-11ea-9941-8f851ac138d1.png">

**Comment by bimawa** [comment]
Yea, thank you for PR!!! It's what we need!
@amaurydavid can you review it and merge?

**Comment by amaurydavid** [comment]
The extension was developed before the Zeplin API supported StyleGuides (https://github.com/zeplin/zeplin-extension-documentation/pull/48) and until now I didn't used them.
It should be the reason why only local styles are exported.
I'll look at the PR ;)

**Comment by amaurydavid** [comment]
I've just released 0.3.1 which supports shared styleguides.
Thanks for the heads-up guys ;)
